services:
  web-app:
    container_name: web_app
    image: web_app:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - web-app:/zmey_shop
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
    depends_on:
      - database
      - redis

  database:
    container_name: database_postgres
    image: postgres:15.6-bookworm
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_USER=${USER_DB}

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:7
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
  
  redis:
    image: redis:7.2.4-bookworm
    hostname: redis
    volumes:
      - redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: [redis-server, /usr/local/etc/redis/redis.conf]

volumes:
  web-app:
  db_data:
  pgadmin4:
  redis: