services:
  web-app:
    container_name: web_app
    image: web_app:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./zmey_shop:/zmey_shop
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
    depends_on:
      - database

  database:
    container_name: database_postgres
    image: postgres:15.6-bookworm
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_USER=${USER_DB}

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:7
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

# volumes:
#   db_data:
#   pgadmin4: