# Generated by Django 4.2 on 2023-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='имя')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL')),
                ('color', models.CharField(max_length=60, verbose_name='цвет')),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежды',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['slug'], name='goods_goods_slug_7f4ed1_idx'),
        ),
    ]
