# Generated by Django 4.2 on 2024-01-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='photo',
        ),
    ]
