# Generated by Django 4.2 on 2024-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='main_photo', verbose_name='основное_фото'),
        ),
    ]
