# Generated by Django 4.2 on 2024-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='additional_materials',
            field=models.CharField(max_length=100, null=True, verbose_name='Доп. материалы'),
        ),
        migrations.AddField(
            model_name='goods',
            name='article',
            field=models.IntegerField(null=True, unique=True, verbose_name='Артикль'),
        ),
        migrations.AddField(
            model_name='goods',
            name='composition',
            field=models.CharField(max_length=100, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(max_length=5000, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='yarn',
            field=models.CharField(max_length=100, null=True, verbose_name='Название пряжи'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='color',
            field=models.CharField(max_length=60, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='main_photo', verbose_name='Основное_фото'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Имя'),
        ),
    ]
