# Generated by Django 4.2 on 2024-02-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_categorygoods_goods_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygoods',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
