# Generated by Django 4.2 on 2024-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'ordering': ['id'], 'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='фото'),
        ),
    ]
